# Java Maven CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

parameters:
  deploy_release:
    type: boolean
    default: false
    
jobs:
  build:
    filters:
      branches:
        only: master
        
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:21.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run: 
          name: Adjusting toolchain
          command: sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
     
      # run tests!
      - run: 
          name: Running tests
          command: mvn integration-test -t ci-toolchains.xml

      
  deployment:
    filters:
      branches:
        only: master

    docker:
      # specify the version you desire here
      - image: cimg/openjdk:21.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      
    steps:
      - checkout

      - run:
          name: Adjusting toolchain
          command: sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
        
      # run deployment!
      - run:
          name: Deploying snapshots
          command: mvn deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml -t ci-toolchains.xml
      
workflows:
  build_deploy:
    unless: << pipeline.parameters.deploy_release >>
    jobs:
      - build
      - deployment:
          requires:
            - build
            
  build_deploy_release:
    when: << pipeline.parameters.deploy_release >>
    jobs:
      - build
      - deployment:
          requires:
            - build