# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:21.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run: 
          name: Adjusting toolchain
          command: sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
     
      # run tests!
      - run: 
          name: Running tests
          command: mvn integration-test -t ci-toolchains.xml

      
  deployment:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:21.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run:
          name: Adjusting toolchain
          command: sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
        
      # run deployment!
      - run:
          name: Deploying snapshots
          command: mvn deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml -t ci-toolchains.xml
      
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build