<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>systems.uom</groupId>
		<artifactId>systems-parent</artifactId>
		<version>2.2.2-SNAPSHOT</version>
	</parent>
	<artifactId>systems-quantity</artifactId>
	<name>Units of Measurement Systems Quantities</name>
	<description>Additional quantities for Unit Systems</description>
	<licenses>
        <license>
            <name>BSD 3-Clause</name>
            <url>LICENSE</url>
            <distribution>manual</distribution>
        </license>
    </licenses>
	<!-- Developers and Contributors -->
	<developers>
		<developer>
			<id>dautelle</id>
			<name>Jean-Marie Dautelle</name>
			<email>jean-marie@dautelle.com</email>
			<organization>Airbus</organization>
			<organizationUrl>https://www.airbus.com</organizationUrl>
			<timezone>+1</timezone>
			<roles>
				<role>Architect</role>
				<role>Java Developer</role>
				<role>Spec Lead</role>
			</roles>
		</developer>
		<developer>
			<id>keilw</id>
			<name>Werner Keil</name>
			<email>werner@catmedia.us</email>
			<organization>CATMedia</organization>
			<organizationUrl>http://www.catmedia.us</organizationUrl>
			<timezone>+1</timezone>
			<roles>
				<role>Architect</role>
				<role>Java Developer</role>
				<role>Spec Lead</role>
			</roles>
		</developer>
		<developer>
			<id>otaviojava</id>
			<name>Otávio Gonçalves de Santana</name>
			<email>otaviopolianasantana@gmail.com</email>
			<organization>Individual / SouJava</organization>
			<timezone>0</timezone>
			<roles>
				<role>Expert</role>
				<role>Java Developer</role>
				<role>Spec Lead</role>
			</roles>
		</developer>
		<developer>
			<id>desruisseaux</id>
			<name>Martin Desruisseaux</name>
			<email>martin.desruisseaux@geomatys.com</email>
			<organization>Geomatys</organization>
			<organizationUrl>http://www.geomatys.com</organizationUrl>
			<timezone>+1</timezone>
			<roles>
				<role>Expert</role>
				<role>Java Developer</role>
			</roles>
		</developer>
	</developers>
	<contributors>
        <contributor>
            <name>See contributors.txt</name>
        </contributor>
    </contributors>
	<dependencies>
		<dependency>
			<groupId>javax.measure</groupId>
			<artifactId>unit-api</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>bnd-process</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
			</plugin>
			
			<plugin>
	            <groupId>net.nicoulaj.maven.plugins</groupId>
	            <artifactId>checksum-maven-plugin</artifactId>
	        </plugin>
			
     		<plugin>
	        	<groupId>org.sonatype.central</groupId>
	          	<artifactId>central-publishing-maven-plugin</artifactId>
	       </plugin>
		</plugins>
	</build>
	
	<profiles>
			<profile>
			<id>jdk9-setup</id>
			<activation>
				<jdk>[9,)</jdk>
			</activation>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-compiler-plugin</artifactId>
							<configuration>
								<release>8</release>
							</configuration>
							<executions>
								<execution>
									<id>default-compile</id>
									<configuration>
										<release>9</release>
										<source>9</source>
										<target>9</target>
									</configuration>
								</execution>
								<execution>
									<id>base-compile</id>
									<goals>
										<goal>compile</goal>
									</goals>
									<configuration>
										<excludes>
											<exclude>module-info.java</exclude>
										</excludes>
									</configuration>
								</execution>
							</executions>
						</plugin>
					</plugins>
				</pluginManagement>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>build-helper-maven-plugin</artifactId>
						<executions>
							<execution>
								<id>add-jdk9-source</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>add-source</goal>
								</goals>
								<configuration>
									<sources>
										<source>src/main/jdk9</source>
									</sources>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<url>http://www.uom.systems</url>
	<scm>
		<url>https://github.com/unitsofmeasurement/uom-systems.git</url>
	</scm>
</project>